# Generated by Django 3.2 on 2021-12-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('poptitle', models.CharField(max_length=50)),
                ('popauthor', models.CharField(max_length=50)),
                ('pophead', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('popthumbnail', models.ImageField(default='', upload_to='media/images')),
            ],
        ),
    ]
