# Generated by Django 3.2 on 2021-12-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpost',
            name='poptitle',
            field=models.CharField(max_length=500),
        ),
    ]
