# Generated by Django 3.2 on 2021-12-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='covid_price',
            field=models.FloatField(),
        ),
    ]
