# Generated by Django 3.2 on 2021-12-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_covid_covid_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DERMA', 'Dermatology'), ('DIAB', 'Diabetes'), ('DEP', 'Depression'), ('DEN', 'Dental'), ('FRAC', 'Fracture'), ('EYE', 'Eyecare'), ('WOM', 'Womens'), ('HAIR', 'Hairfall'), ('BP', 'Blood'), ('COVID', 'Corona')], default='', max_length=20),
        ),
    ]
