# Generated by Django 3.2 on 2021-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20211205_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DERMA', 'Dermatology'), ('DIAB', 'Diabetes'), ('DEP', 'Depression'), ('DEN', 'Dental'), ('FRAC', 'Fracture'), ('EYE', 'Eyecare'), ('WOM', 'Womens'), ('HAIR', 'Hairfall'), ('BP', 'Blood'), ('COVID', 'Corona'), ('OXY', 'Oxygen')], default='', max_length=20),
        ),
    ]
